In [3]:
import numpy as np


In [4]:
def normaliziraj_vektorsko(vektor):
    return vektor / np.max(np.abs(vektor))

In [5]:
def konv_frekvenca_mono(signal, impulz):

    X = np.fft.fft(signal, n=signal.shape[0]+impulz.shape[0]-1, axis=0)
    H = np.fft.fft(impulz, n=signal.shape[0]+impulz.shape[0]-1, axis=0)

    Y = X*H

    dolzina = signal.shape[0] + impulz.shape[0] - 1

    y2 = np.zeros((dolzina, 2))
    # inverzna fourierova transformacija rekonstruira originalni signal 
    # pri tem je običajno potrebno vzeti samo realni del (tudi ta funkcija vrne kompleksna števila)
    y2 = np.real(np.fft.ifft(Y, axis=0))
    y2 = np.reshape(y2, (-1, 1))
    y2 = normaliziraj_vektorsko(y2)
    return y2


In [6]:
def konv_frekvenca_stereo(signal, impulz):

    X = np.fft.fft(signal, n=signal.shape[0]+impulz.shape[0]-1, axis=0)
    H = np.fft.fft(impulz, n=signal.shape[0]+impulz.shape[0]-1, axis=0)

    Y = X*H

    dolzina = signal.shape[0] + impulz.shape[0] - 1

    y2 = np.zeros((dolzina, 2))
    # inverzna fourierova transformacija rekonstruira originalni signal 
    # pri tem je običajno potrebno vzeti samo realni del (tudi ta funkcija vrne kompleksna števila)
    y2 = np.real(np.fft.ifft(Y, axis=0))
    y2 = np.reshape(y2, (-1, 2))
    y2 = normaliziraj_vektorsko(y2)
    return y2

In [7]:
if __name__ == '__main__':
    x = np.array([1,2,3,4,5,6,7,8,9,10])
    h = np.array([1,2,1])
    x = normaliziraj_vektorsko(x)
    h = normaliziraj_vektorsko(h)
    a = konv_frekvenca_mono(x,h)

    print(x,"\n","\n", h, "\n","\n", a)

    x1 = np.array([[1,2], [3,4], [5,6], [7,8], [9,10], [11,12], [13,14], [15,16], [17,18], [19,20]])
    h1 = np.array([[1,2],[2,1], [1,2]])
    x1 = normaliziraj_vektorsko(x1)
    h1 = normaliziraj_vektorsko(h1)
    b = konv_frekvenca_stereo(x1,h1)

    print(x1,"\n","\n", h1, "\n","\n", b)

[0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ] 
 
 [0.5 1.  0.5] 
 
 [[0.02777778]
 [0.11111111]
 [0.22222222]
 [0.33333333]
 [0.44444444]
 [0.55555556]
 [0.66666667]
 [0.77777778]
 [0.88888889]
 [1.        ]
 [0.80555556]
 [0.27777778]]
[[0.05 0.1 ]
 [0.15 0.2 ]
 [0.25 0.3 ]
 [0.35 0.4 ]
 [0.45 0.5 ]
 [0.55 0.6 ]
 [0.65 0.7 ]
 [0.75 0.8 ]
 [0.85 0.9 ]
 [0.95 1.  ]] 
 
 [[0.5 1. ]
 [1.  0.5]
 [0.5 1. ]] 
 
 [[0.01111111 0.04444444]
 [0.05555556 0.11111111]
 [0.13333333 0.22222222]
 [0.22222222 0.33333333]
 [0.31111111 0.44444444]
 [0.4        0.55555556]
 [0.48888889 0.66666667]
 [0.57777778 0.77777778]
 [0.66666667 0.88888889]
 [0.75555556 1.        ]
 [0.61111111 0.62222222]
 [0.21111111 0.44444444]]
