In [321]:
import numpy as np

def generiraj_vektor_nakljucno(stevilo_vzorcev):
    sampl = np.random.uniform(low=0.0, high=1.0, size=(stevilo_vzorcev,1))
    return sampl


In [322]:
def beri_zvok_mono(pot_do_datoteke):
  from scipy.io import wavfile
  Fs, y = wavfile.read(pot_do_datoteke)

  if y.ndim == 1:
    mono = y
    mono = mono.reshape((mono.shape[0], 1))
    norm = max(map(abs, mono))
    return mono / norm

  else:
   # combined = np.concatenate((y))
    #combined = np.zeros((int(y.size/2),1))

    ##  combined[i] = (y[i][0]) 
#mono = y
    #mono1 = y
    #combined = np.concatenate((mono, mono1), axis=1)
    combined = np.zeros((int(y.size/2),1))

    for i in range(combined.size):
      combined[i] = (y[i][0] + y[i][1]) / 2
    
    #combined = np.reshape(combined.size, 1)
    norm = np.max(np.abs(combined))

    #combined = np.concatenate([y,y])
    #norm = np.max(np.abs(combined))
    #combined = np.mean(y,axis=1)
    #y = np.concatenate([y,y])
   # y.reshape(int(y.size/2), 2)
    #norm = np.linalg.norm(y)
    #norm = max(map(abs, y))
    return combined / norm


In [323]:
beri_zvok_mono("stereo2.wav")

array([[ 2.93823243e-09],
       [ 1.41995218e-01],
       [ 2.81112896e-01],
       ...,
       [-4.14535093e-01],
       [-2.81114236e-01],
       [-1.41996605e-01]])

In [324]:
def beri_zvok_stereo(pot_do_datoteke):
    from scipy.io import wavfile
    Fs, y = wavfile.read(pot_do_datoteke)


    if y.ndim == 1:
       # stereo = np.array(2*[y])
        #stereo = y
        #stereo = np.append(stereo, 2)
        #stereo = np.array(y)
        #stereo = stereo.reshape(2,-1)
        #stereo = stereo.reshape((stereo.shape[0], 1))
       # y = np.reshape((y.shape[0]), -1)
        #y.reshape(int(y.size/2),1)
        #y = 2*[y]
        #stereo.reshape(int(stereo.size/2),1)
        #stereo = np.tile(y,(2,1))
       # stereo = y
        #stereo = 2*[y]
        #stereo.reshape(int(stereo.size),1)
        stereo = np.zeros([y.size,2])

        for i in range(y.size):
            stereo[i][0] = y[i]
            stereo[i][1] = y[i]

        #stereo = np.stack((y,y))
        norm = max(map(abs, y))
        return stereo / norm
         
    else:
        stereo = y
        #norm = np.linalg.norm(stereo, 1)
        #norm = np.max(np.abs(stereo))
        return normaliziraj_vektorsko(stereo)
        #return stereo / norm



In [325]:
beri_zvok_stereo("churchbell.wav")

array([[-1.00631875e-02, -1.00631875e-02],
       [-1.09992979e-02, -1.09992979e-02],
       [ 3.88485841e-03,  3.88485841e-03],
       ...,
       [-4.68055231e-05, -4.68055231e-05],
       [ 4.68055231e-05,  4.68055231e-05],
       [-9.36110461e-05, -9.36110461e-05]])

In [326]:
def normaliziraj(vektor):
    #normalized_v = vektor / np.sqrt(np.sum(vektor**2))
    norm = np.max(np.abs(vektor))
    return vektor / norm
    #return normalized_v

In [327]:
def normaliziraj_vektorsko(vektor):
    return vektor / np.max(np.abs(vektor))

In [328]:
import timeit

def testiraj_cas_izvajanja(vektor):
    
    starttime = timeit.default_timer()
    #print("Čas začetka je: ", starttime)
    normaliziraj(vektor)
    time = timeit.default_timer() - starttime
    #time1 = (timeit.default_timer() - starttime)

    starttime2 = timeit.default_timer()
    #print("Čas drugega začetka je: ", starttime2)
    normaliziraj_vektorsko(vektor)
    time2 = timeit.default_timer() - starttime2
    #print("Čas drugega izvajanja je:", timeit.default_timer() - starttime)
    #time2 = (timeit.default_timer() - starttime2)
    result = np.array([
        [time, time2]
 ])
    return result
    
    

In [329]:
#generiraj_vektor_nakljucno(5)
#beri_zvok_mono("churchbell.wav")

#beri_zvok_stereo("churchbell.wav")

v = np.random.rand(10)
#normaliziraj(v)
normaliziraj_vektorsko(v)
#testiraj_cas_izvajanja(v)

array([1.        , 0.90618466, 0.03263853, 0.00109919, 0.07735495,
       0.56582696, 0.4623104 , 0.1211963 , 0.22347264, 0.82226997])

In [330]:
if __name__ == '__main__':
    v = np.random.rand(10)
    print(testiraj_cas_izvajanja(v))

[[3.85000001e-05 1.15000000e-05]]
